# Generated by Django 5.1.6 on 2025-02-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=20)),
                ('violation_time', models.DateTimeField(auto_now_add=True)),
                ('fine_amount', models.IntegerField(default=500)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
