# Generated by Django 5.0.6 on 2025-02-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='violation_time',
            field=models.CharField(max_length=20),
        ),
    ]
