# Generated by Django 5.1.6 on 2025-02-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='status',
            field=models.CharField(default='Not Paid', max_length=20),
        ),
    ]
