# Generated by Django 5.0.6 on 2025-02-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0003_alter_violation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='image',
            field=models.ImageField(upload_to='violations/'),
        ),
    ]
