# Generated by Django 5.0.6 on 2025-02-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challan', '0004_alter_violation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
